# Generated by Django 6.0.5 on 2026-05-08 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha'),
        ),
    ]
