# Generated by Django 6.0.5 on 2026-05-10 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_cliente_nombre_fc953b_idx_and_more'),
        ('medicamentos', '0004_medicamento_medicamento_nombre_f6e070_idx_and_more'),
        ('ventas', '0002_detalleventa_created_at_alter_comprobante_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha', db_index=True),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['id_cliente'], name='comprobante_id_clie_213dca_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['id_usuario'], name='comprobante_id_usua_54e779_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_medicamento'], name='detalle_ven_id_medi_16cd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['id_comprobante'], name='detalle_ven_id_comp_970a7b_idx'),
        ),
    ]
