# Generated by Django 6.0.5 on 2026-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_comprobante_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
