# Generated by Django 6.0.5 on 2026-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_add_subtotal_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=20),
        ),
    ]
