# Generated by Django 6.0.5 on 2026-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_cargo_created_at_usuario_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
