# Generated by Django 6.0.5 on 2026-05-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='cliente_nombre_fc953b_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_documento'], name='cliente_numero__994970_idx'),
        ),
    ]
