# Generated by Django 6.0.5 on 2026-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_cliente_nombre_fc953b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
