# Generated by Django 6.0.5 on 2026-05-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'presentacion',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='medicamentos.categoria')),
                ('id_laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.PROTECT, to='medicamentos.laboratorio')),
                ('id_presentacion', models.ForeignKey(db_column='id_presentacion', on_delete=django.db.models.deletion.PROTECT, to='medicamentos.presentacion')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.PROTECT, to='medicamentos.unidad')),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='StockMedicamento',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
            options={
                'db_table': 'stock_medicamento',
            },
        ),
    ]
