# Generated by Django 6.0.5 on 2026-05-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_categoria_created_at_laboratorio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
