# Generated by Django 6.0.5 on 2026-05-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_medicamento_imagen_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['nombre'], name='medicamento_nombre_f6e070_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmedicamento',
            index=models.Index(fields=['id_medicamento'], name='stock_medic_id_medi_7eacb6_idx'),
        ),
    ]
